### ISSUE TITLE
Pinned tabs / whitelist

### ISSUE THREAD

**Issue by Esteban-Rocha** [gilgold/tabox#18]
First thanks for the ext, works great. I may be missing something so I wonder if there is a way of avoiding pinned tabs to get saved? I had to manually edit the list to have **only** non pinned tabs in the group.

If this feature is not implemented, then consider this as a request, I'm sure that a bunch of people will appreciate this.

Thank you!

**Comment by gilgold** [comment]
Hey Esteban! 
Thanks for the suggestions!
I will try to add that to the next version.
For now, you can also choose to save only highlighted tabs by clicking the first non pinned tab and shift + click the last tab in the row to highlight all tabs in that range.
When you open Tabox, it will offer to only save those highlighted tabs.

**Comment by Esteban-Rocha** [comment]
@gilgold Thank you so much for the tip, 😁 👏🏻

**Comment by gilgold** [comment]
Done, will be included in v3.5.1

**Comment by Esteban-Rocha** [comment]
@gilgold Awesome work, thank you so much!
