### ISSUE TITLE
Exporting tabs to file does not work properly

### ISSUE THREAD

**Issue by smaragdus** [gilgold/tabox#2]
Hello,

When I try to export saved tabs to file I get a text file with the following content:

`undefined`

This happened any time I tried to export saved tabs to file.

As a result the exported file is invalid and cannot be used for importing.

So on my end the export feature of [Tabox](https://github.com/gilgold/tabox) (version **3.2.2** installed from [Chrome Web Store](https://chrome.google.com/webstore/detail/tabox-save-and-share-tab/bdbliblipiempfdkkkjohnecmeknnpoa)) does not work right.

I am using [Cent Browser](https://www.centbrowser.com/) [version](https://www.centbrowser.com/history.html) **4.2.10.171** (portable, x32).

I would appreciate if the developer is able to reproduce and confirm the problem with export feature of the extension.

Regards

**Comment by gilgold** [comment]
Hey @smaragdus ! 
Thanks for reporting the issue.
Tabox was not designed to run on browsers other than Chrome - I will look into making it compatible with Cent Browser and other Chromium based browsers.

**Comment by smaragdus** [comment]
@gilgold 

Thank you for the super fast response!

I was not aware that the extension was not supposed to work with Chromium forks. I know that the latest stable version of Cent Browser is a bit old (from _2020-04-23_).

If you have time and plan to develop the extension further I may suggest some enhancements if you don't mind.

Regards

**Comment by gilgold** [comment]
Sure thing, please feel free to suggest what ever you like, I will do my best to get it done

**Comment by gilgold** [comment]
A fix for this issue has been merged and submitted to the Chrome Web Store for publishing.
Version 3.2.3 should be out later today

**Comment by smaragdus** [comment]
@gilgold 

You are extremely quick in responding, confirming and fixing issues! I appreciate your helpfulness, thanks.

I have just checked version **3.2.3** and I cam confirm that both export and import of tab sets work fine. So I will close this issue.

When I have time I will open a few new issues about possible enhancements of your extension.

Best regards
