### ISSUE TITLE
Update icon overlaps the download icon

### ISSUE THREAD

**Issue by sevdalin** [gilgold/tabox#20]
The update icon overlaps the download icon.

I'm using Chrome Version 90.0.4430.212 and Tabox 3.3.3

![Annotation 2021-05-15 154836](https://user-images.githubusercontent.com/25548429/118361860-d9935c80-b595-11eb-9df3-9c746899ccb8.JPG)

**Comment by gilgold** [comment]
Thanks for reporting @sevdalin ! I will fix it ASAP!

**Comment by gilgold** [comment]
A fix has been issued in version 3.3.4 and is pending publish to the Chrome Web Store.
