### ISSUE TITLE
When opening saved tabs they are added to the current window

### ISSUE THREAD

**Issue by sevdalin** [gilgold/tabox#21]
When opening saved group of tabs, they are added to the current Chrome window and get mixed with the rest of the taps you have opened.
Not too long ago when you open the save tabs they were opening separately in a new Chrome window as it should be, so it can be kept separate and help you work better. Is this changed on purpose or not? Can you please make it as it was, because it was a huge difference and a lot more helpful for the user.

I'm using Chrome Version 90.0.4430.212 and Tabox 3.3.3

**Comment by gilgold** [comment]
Hey @sevdalin ! Can you make sure the toggle to "open in a new window" is on? 
![image](https://user-images.githubusercontent.com/10116036/118414383-d36eb000-b669-11eb-85da-72fe52c14f34.png)

**Comment by sevdalin** [comment]
Indeed the toggle was off. May be this happened after some update, because I did not turned it off intentionally. However, my bad. Closing this invalid defect.
