### ISSUE TITLE
Can't login & Sync

### ISSUE THREAD

**Issue by sevdalin** [gilgold/tabox#22]
Once I login with my account (I give all possible permissions) the first second it says success and I can see I'm logged and the next second I got error and I'm logged out. I can't sync my data or log in. I used "Restore collection from version 3.4.9" and I get my saved bookmarks but if I close the extension window they disappear again. I'm not sure after which version the problem occurred because I haven't used it in a while.

![success](https://user-images.githubusercontent.com/25548429/136078311-42c8ef78-52fc-4a8b-8714-4fd282c03393.JPG)
![error](https://user-images.githubusercontent.com/25548429/136078305-733706fe-9ef2-4b60-8bbb-9f33d9ef9da3.JPG)

**Comment by gilgold** [comment]
Possibly related to #19 
Thank you for the info and screenshots!
I am looking into it.

**Comment by gilgold** [comment]
Though I was not able to reproduce the issue, I made some changes to the sync process in v3.5.1 that hopefully fix this.
Please reopen the issue if it still happens in v3.5.1 (currently pending publish in the Chrome store)
