### ISSUE TITLE
google sign in button crashes microsoft edge

### ISSUE THREAD

**Issue by kapdon** [gilgold/tabox#27]
edge Version 97.0.1072.55 (Official build) (64-bit)

click on the button and browser closes.

**Comment by n2don** [comment]
edge Version 97.0.1072.55 (Official build) (64-bit)

click on the button and browser closes.

**Comment by adamhill** [comment]
I can confirm this crash.

I have a brand new Windows 11 instance. Setup Edge and Tabox. 

Locally it is working fine. But as soon as I click the Google Login button, Edge crashes.

Latest Edge on the Mac does not crash (I am in the Dev channel)

If you need any more repro details I am happy to collect logs or attach a debugger.

Thanks for the awesome tool!

**Comment by gilgold** [comment]
Thanks for the information! I am looking into this

**Comment by gilgold** [comment]
This may have been fixed by Edge, can you update Edge to the latest version and try again? 
Also if you have any security extensions suck as BitDefender or other antivirus extensions, can you try disabling those to see if they may be causing it? 

Thanks!

**Comment by gilgold** [comment]
Closing for now, if anyone sees it happening again on the latest version of Edge please reopen
