### ISSUE TITLE
Add a way to automatically save sessions every 15min or just dynamically whenever the tab updates or closes

### ISSUE THREAD

**Issue by Droyk** [gilgold/tabox#28]
It's a great way to enhance functionality! like a tab session manager https://chrome.google.com/webstore/detail/tab-session-manager/iaiomicjabeggjcfkbimgmglanimpnae 
I don't want to use two extensions make it one-stop for all!

**Comment by gilgold** [comment]
Thanks @Droyk ! I will look into adding this feature

**Comment by Droyk** [comment]
before going at it may I suggest reading this article https://www.interaction-design.org/literature/article/a-simple-introduction-to-lean-ux recently can across it! felt so relatable! it had everything I think devs should think about when developing anything. always look at what can be done to make the user experience more productive! always stay one step ahead!

**Comment by gilgold** [comment]
Added in v3.5.9
