### ISSUE TITLE
Support auto-updating collections

### ISSUE THREAD

**Issue by gilgold** [gilgold/tabox#3]
Add support for collections that can auto update as the user opens and closes tabs or changes anything in the window associated with the collection.

Window -> Collection association can be created when the user saves a collection or when opening one.

This functionality requires we collect window information, as suggested in #2

**Comment by jorgitobg** [comment]
Would be GREAT to have auto-update for collections.... doing manually doesnt work because you can forget.

Do you have some ETA for this update?

**Comment by gilgold** [comment]
Looking into this now.

**Comment by gilgold** [comment]
In final staging of testing, will be released in the next few days

**Comment by gilgold** [comment]
v3.5.3 has been submitted to the chrome and edge stores. pending review process.
This includes auto updating collections (in BETA, need to be enabled in the settings menu, it will be off by default)
