### ISSUE TITLE
Problems importing from exported file

### ISSUE THREAD

**Issue by wksantiago** [gilgold/tabox#30]
I was able to export all my collections to a file, by clicking the settings icon and choose to export all collections.

When I tried to import it does not do anything.

Is this normal??

**Comment by gilgold** [comment]
Hey!
I don't see any issues when I attempt to do this myself, would you mind either attaching the exported file here or sending it over to info@tabox.co so I can check to see what the issue is?

Thanks!

**Comment by wksantiago** [comment]
File sent to info@tabox.co

**Comment by wksantiago** [comment]
For some reasons today when I opened the Browser all tabs disappeared

**Comment by gilgold** [comment]
Thank you!
I was ale to successfully import the file and all its collections. 
Here is something you can try to do:
1. Go to the Extensions page in Chrome
2. Disable or remove Tabox 
3. Re-enable / re-install Tabox
4. Try to import the file again

If that does not work, there could be something else interfering - perhaps some other extension - in that case, try to disable some security /  tab blocking / ad blocking extension you may have and see if those are causing this issue.

Let me know if you are able to resolve this problem using the steps above.

Apologies for the inconvenience!

**Comment by wksantiago** [comment]
OK I tried to import on a Chromebook and it worked.

But as soon as I linked to my google account it synced with the google backup hidden file which is empty and it synced empty.

Where can I remove the backup file in my google drive that is hidden?

**Comment by gilgold** [comment]
The sync file is located in a hidden folder that can only be accessed programmatically. 
You could try to enable sync first, then import the file - that should cause the sync file to get updated with the imported collections

**Comment by wksantiago** [comment]
Yes that worked.  I wonder if there is a log to see why the import function on the other browsers did not work?
Thanks,

**Comment by wksantiago** [comment]
I did see that "Restore collections from version" 3.5 option,

Is no longer available on the PC other browsers after sync.

Was there a recent upgrade form v3.5 to v3.5.1?

**Comment by gilgold** [comment]
v3.5.1 is the current version. The option to restore form previous version only appears after a Tabox has updated to a new version, in case there was some problem with the update process

**Comment by wksantiago** [comment]
Strange what happened but glad it was solved.

Thanks,
