### ISSUE TITLE
TabGroups not opening properly

### ISSUE THREAD

**Issue by kyletimmermans** [gilgold/tabox#39]
<div>Hello, I wanted to let you know that I love Tabox and I use it all the time!</div>
</br>
<div>I recently started using Tabox v3.5.4 and noticed an issue when trying to open my collections in a new or current window. When I try to open a collection, the tabs won't open in their colored TabGroups, but rather as individual tabs only. I was able to recreate the issue on another machine with a fresh install of Tabox v3.5.4 as well. I tested this on Chrome v100.0.4896.127 on MacOS. I've also added a video to show the issue first hand.</div>
</br>
<div>Note: This only seems to happen to larger groups of tabs, E.g. a collection of 72 tabs in 10 groups does not work properly, but a collection of 23 tabs in 5 groups does work properly.</div>
</br>

https://youtu.be/aIRp8Y3BRoc

**Comment by ghost** [comment]
Hello, I have same problem!!!

**Comment by gilgold** [comment]
Thanks for reporting! I am aware of the issue and working on a fix. Should be out in a few days (depending on the time it takes for the version to be approved on the Chrome and Edge stores)

**Comment by wksantiago** [comment]
Thanks @gilgold is there a way to get this new update without waiting for Chrome and Edge stores?

**Comment by gilgold** [comment]
@wksantiago i am still working on the fix, found a few more issues during testing. Hope to have it out ASAP. 
Appreciate your patience!

**Comment by wksantiago** [comment]
thanks

**Comment by gilgold** [comment]
Fixed - Waiting for approval on Chrome and Edge web stores.
