### ISSUE TITLE
Broken UI when scrollbar appears for longer list

### ISSUE THREAD

**Issue by sevdalin** [gilgold/tabox#4]
Hi team. I have noticed that when my saved tabs become more and a scrollbar appears so they can be listed in the popup, the message "X tabs" on each group become broken as string "tabs" is going on a new line, because the space left from the scrollbar is less and it can't fit.

**Comment by gilgold** [comment]
Hey @sevdalin thanks for reporting the issue.
I was not able to reproduce it locally, can you post a screenshot and more information about the resolution your screen is set to? 
Thanks!

**Comment by sevdalin** [comment]
![defect](https://user-images.githubusercontent.com/25548429/103041418-03180100-457f-11eb-821d-6caaae20f1ac.JPG)

My resolution is set to maximum (1920x1080 Full HD).

**Comment by gilgold** [comment]
Thanks, I will look into that!

**Comment by gilgold** [comment]
The issue has been fixed in version 3.2.4 - It's pending publish in the Chrome Web Store now and should be public soon.
Please reopen the issue if you still see the problem after updating to version 3.2.4.

Thanks!

**Comment by sevdalin** [comment]
@gilgold thanks for the fast fix. I will update when it's available.
And just one suggestion. If you have some time, can you make the list names editable?
