### ISSUE TITLE
Cannot import collections on edge (linux)

### ISSUE THREAD

**Issue by Loskoss** [gilgold/tabox#42]
I exported collection in edge windows now trying to import on edge linux doesnt work.

**Comment by gilgold** [comment]
There should not be any difference between Edge in windows and Linux, is there an error after selecting a file to import?

**Comment by wksantiago** [comment]
Also on brave and the export file has lots of data so it is not empty and when you import there is nothing

**Comment by gilgold** [comment]
Might be a linux issue. Can you try the following to help debug:
1. Enable developer mode in the browser (go to the extensions page and toggle on the switch for "Developer Mode")
2. Right click the Tabox icon and select "Inspect popup"
3. In the developer tools window that pops up, go to the console tab
4. In Tabox, try to import the file
5. In the developer tools console - see if there are any error messages

Thanks!

**Comment by wksantiago** [comment]
No errors and all imports came in. 

But there is a caviat.

Yesterday my laptop HD crashed and had to recover from scratch thus a fresh Brave Browser.

So I belive it was a security setting on my Browser that I had that hardened so much it prevented the import.

**Comment by gilgold** [comment]
I see, sorry about your HD but glad this issue was sorted!

**Comment by wksantiago** [comment]
I will try to harden the setting in my Browser, once I find those notes, then I will import again to see if I can replicate the issue.

Will keep all posted.

Thanks,
