### ISSUE TITLE
Feature Request: Tab Counter on the Extension Button

### ISSUE THREAD

**Issue by pranavAbe** [gilgold/tabox#47]
## Idea: 
A toggle in the settings that enabled a **counter** for the **number of tabs open** to be displayed on the extension button. 

An additional flair to this will be having the counter take on a **colour gradient** (*white -> red* indicating *low -> high*) according to the **system load** from the number of tabs open. 

This feature is found in a competing session manager extension Session Buddy, and I thought it would be nice to have the feature on Tabox too, and hopefully easy to implement. 

## Expected Look: 
![image](https://user-images.githubusercontent.com/29583966/199208194-9a822fd0-3a5b-4e4e-91d4-7287311c7d44.png)

**Comment by gilgold** [comment]
Hey @pranavAbe ! Thanks for the suggestion! 
How would you suggest the count be considered when there are multiple windows with multiple tabs? Should it count the total number of tabs across all windows or just for the current window?

**Comment by pranavAbe** [comment]
Hey, thanks for the prompt reply @gilgold !
I'm all for customisability for the end user, so maybe offering a toggle to set it to count both the number of tabs in each window or count the total number of tabs from all windows would be great.

**Comment by gilgold** [comment]
I will look into adding that! Thanks!

**Comment by gilgold** [comment]
Fixed in v3.5.8 - pending publish in the Chrome and Edge stores
