### ISSUE TITLE
about:blank

### ISSUE THREAD

**Issue by DoctorMidnite** [gilgold/tabox#53]
recently when i am using tabox and opening a collection of tabs for animeplanet.com some of them turn into blank pages even though they got a url and were loading but suddenly they turn into blank page Note this issue started about 20 days ago or something close to that i have been using this extension for a year or so
![box](https://user-images.githubusercontent.com/118439192/202421866-2924c616-99cd-49f4-9f1d-aa18835c1a43.png)

**Comment by gilgold** [comment]
Hey @DoctorMidnite can you confirm this is still happening on v3.5.8 that was released yesterday?

**Comment by DoctorMidnite** [comment]
Yes Ty **@gilgold** its working perfectly now thanks alot

**Comment by gilgold** [comment]
Glad to hear it!
