### ISSUE TITLE
'open-collection' Commands Opening Collections in New Chrome Window

### ISSUE THREAD

**Issue by sheral2** [gilgold/tabox#57]
Currently, when using the "open-collection-1" keyboard shortcut command (default ctrl+shift+1), it opens the tab collection in a new window rather than the current widow (the issue occurs with using the other open-collection command keyboard shortcuts as well). Would it be possible to update this to open these tab collections in the same window when using the keyboard commands?

I feel like the issue _might_ be located in lines 232-240, but I'm not too familiar with js nor chrome apps (or anything else for that matter) and I'm taking a guess tbh.

Thank you!

[https://github.com/gilgold/tabox/blob/b2c19bafec31bbbab94fbf65be3bb3c815b634fe/chrome/background.js#L232-L240](https://github.com/gilgold/tabox/blob/b2c19bafec31bbbab94fbf65be3bb3c815b634fe/chrome/background.js#L232-L240)

**Comment by gilgold** [comment]
Hey @sheral2 ! 
Thanks for reporting the issue!
You are correct, the current behavior is to open a new window each time a keyboard shortcut is used.
I will change it match the behavior set in the Tabox popup window (where you can toggle new window option on or off).
This will be added to the upcoming version (v3.5.9).

Thanks again!

**Comment by gilgold** [comment]
This is fixed in v3.5.9. please reopen the issue if you still have problems.
