### ISSUE TITLE
Generate a URL per Collection so they can be triggered to open from 3rd parties (thinking particularly about https://www.alfredapp.com/)

### ISSUE THREAD

**Issue by sebastianmurillonader** [gilgold/tabox#6]
Reference on how it could work here: https://twitter.com/sebmurillonader/status/1427337564713889804

**Comment by gilgold** [comment]
Thanks for the feature request!
I will be looking into this and if it's possible to create such URLs in chrome extensions I will add this feature to one of the upcoming versions.

**Comment by sebastianmurillonader** [comment]
Thanks, Gil!


I and all the team at 8020 have talked about this and we'd find it super helpful for our workflows! I am happy to share it again or share the process in Twitter to try and get you some new followers/customers from the No Code community .



—
Sebastián Murillo | @sebmurillonader

--- original message ---
On August 19, 2021, 8:41 PM CDT ***@***.*** wrote:



Thanks for the feature request!

I will be looking into this and if it's possible to create such URLs in chrome extensions I will add this feature to one of the upcoming versions.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---

**Comment by gilgold** [comment]
After looking into this issue, I found that it is not possible to generate a URL that will lunch Tabox and open a collection. 
Instead, the only thing I can do is provide keyboard shortcuts for the first 4 collections. 

Using the combination of `Ctrl/Cmd + Shift + 1,2,3 or 4` will lunch the corresponding collection from your Tabox list.

In Alfred, you can build a workflow to first open Chrome and then inject the keyboard shortcut you want to open the collection.

Chrome limits an extension to a max of 4 shortcuts so that is the best I can do. 
Hopefully this helps.

**Comment by gilgold** [comment]
Reference on how this can be done: 
Opening chrome (with specific profile) https://www.alfredforum.com/topic/3242-google-chrome-with-specific-user/ 
Sending a keyboard shortcut: https://www.alfredapp.com/help/workflows/outputs/dispatch-key-combo/

**Comment by sebastianmurillonader** [comment]
Thanks, so much sir! This will be very helpful for sure.


All the best.



—
Sebastián Murillo | @sebmurillonader

--- original message ---
On September 9, 2021, 2:12 PM CDT ***@***.*** wrote:



Reference on how this can be done:

Opening chrome (with specific profile) https://www.alfredforum.com/topic/3242-google-chrome-with-specific-user/

Sending a keyboard shortcut: https://www.alfredapp.com/help/workflows/outputs/dispatch-key-combo/

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---

**Comment by gilgold** [comment]
Added to v3.5, scheduled for release later today
